### ISSUE TITLE
About the project

### ISSUE THREAD

**Issue by Pravesh-Jamgade** [aothms/IfcOpenShell_CGAL#18]
Hello,
I'm wondering what these project does ?
Can you please tell me , in what ways it is different from IfcOpenShell ?
Is it for the conversion of Ifc2citygml?

**Comment by aothms** [comment]
>  Is it for the conversion of Ifc2citygml?

To some extent, yes. In a more general sense it's an attempt to have CGAL as an alternative geometry kernel to the currently used Open CASCADE. At this moment not a great deal of effort is invested in this 'branch', but it's likely going to end up in the 'official' IfcOpenShell version as an alternative implementation that can be selected by the end user at runtime.

For a full idiomatic conversion to CityGML additional effort is required, e.g. to eliminate invisible surfaces. To some extent this is independent of the used geometry kernel, but it is assumed that the arbitrary precision and robust boolean ops of CGAL can likely contribute to this.

As CGAL is widely used in the GIS world, it also provides better interoperability.
